title: Samantha Hamilton: Portfolio
logo: /assets/img/icon.png
description: Hello! I am a Computer Science student at Southern New Hampshire University and a game designer in my spare time. I work as an IT support Engineer for a large online retailer. This website includes samples of my works of code.
show_downloads: true
google_analytics:
theme:
